# Generated by Django 5.1.3 on 2024-11-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_alter_populardestination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populardestination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
