# Generated by Django 5.1.3 on 2024-11-13 01:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_alter_populardestination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populardestination',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
