# Generated by Django 5.1.3 on 2024-11-18 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0005_delete_booking_delete_populardestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestinations',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_image', models.ImageField(upload_to='destinations/')),
                ('destination_location', models.CharField(max_length=50)),
                ('departure_location', models.CharField(max_length=50)),
                ('travel_time_maximum', models.IntegerField()),
                ('travel_time_minimum', models.IntegerField()),
            ],
        ),
    ]
