# Generated by Django 5.1.3 on 2024-11-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularDestinations',
            new_name='PopularDestination',
        ),
    ]
