# Generated by Django 5.2 on 2025-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_booking_number_of_passengers_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
