# Generated by Django 5.2 on 2025-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='departure_location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='transport',
            name='destination_location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
